language: ruby

rvm: 2.2.3

gemfile: Gemfile.ci

# XXX TEMPORARY
sudo: required
services: docker
group: edge
env:
  global:
  - RSPEC_TAGS=mega
# sudo: false
# XXX TEMPORARY

script:
- bundle exec rake rubocop
- git log -1 | if grep -qE '^\s+___RUN_THE_SUITE___' ; then bin/run-suite ; fi
