language: ruby

rvm: 2.2.3

gemfile: Gemfile.ci

# XXX TEMP
# sudo: false
sudo: required
group: edge
services: docker
env:
  global:
  - RSPEC_TAGS=mega
# XXX TEMP

script:
- bundle exec rake rubocop
- git log -1 | if grep -qE '^\s+___RUN_THE_SUITE___' ; then bin/run-suite ; fi
